 version: '3.7'

 services:
  web:
    build: .
    entrypoint: /entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - SQL_ENGINE=django.db.backends.postgresql_psycopg2
      - SQL_DATABASE=postgres
      - SQL_USER=postgres
      - SQL_PASSWORD=.env/PASSWORD
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - /data/postgresql:/var/lib/postgresql
      - /data/postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=.env/PASSWORD
      - POSTGRES_DB=postgres
