 version: '3.7'

 services:
  web:
    build: .
    entrypoint: /entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - SQL_ENGINE=django.db.backends.postgresql_psycopg2
      - SQL_DATABASE=postgres
      - SQL_USER=postgres
      - SQL_PASSWORD=.env/PASSWORD
      - SQL_HOST=postgres
      - SQL_PORT=5432
      - DATABASE=postgres
      - DEBUG=1
      - SECRET_KEY=foo
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - /data/postgresql/data:/var/lib/postgresql/data/:rw
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=.env/PASSWORD
      - PGDATA=/var/lib/postgresql/data/
    
