# Generated by Django 3.1.6 on 2021-02-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhitePapers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('symbol', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('content', models.TextField()),
            ],
        ),
    ]
