# Generated by Django 3.1.6 on 2021-04-05 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whitepapers_blog', '0003_auto_20210217_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whitepapers',
            options={'verbose_name': 'WhitePapers', 'verbose_name_plural': 'WhitePapers'},
        ),
    ]
